# Generated by Django 5.0.6 on 2025-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('admission_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('record_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Unknown', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_caste', models.CharField(blank=True, max_length=50, null=True)),
                ('sc_st', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(default='Unknown', max_length=50)),
                ('taluk', models.CharField(max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('sts_no', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('parent_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address_permanent', models.TextField()),
                ('address_temporary', models.TextField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=150, null=True)),
                ('year_of_admission', models.IntegerField()),
                ('year_of_graduation', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('current_semester', models.IntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('last_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('electives', models.TextField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('subjects_taken', models.TextField(blank=True, null=True)),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('twelfth_percentage', models.FloatField(blank=True, null=True)),
                ('fees_paid', models.BooleanField(default=False)),
                ('scholarship_details', models.TextField(blank=True, null=True)),
                ('fee_concessions', models.TextField(blank=True, null=True)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('total_school_days', models.IntegerField(blank=True, null=True)),
                ('days_attended', models.IntegerField(blank=True, null=True)),
                ('character_conduct', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_status', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_exam', models.BooleanField(default=False)),
                ('tc_application_date', models.DateField(blank=True, null=True)),
                ('tc_issue_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
