# Generated by Django 5.0.6 on 2025-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tc_serial_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
