# Generated by Django 5.0.6 on 2025-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_tc_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tc_serial_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
